### ISSUE TITLE
screen doesn't wakeup

### ISSUE THREAD

**Issue by wiebe1971** [thanksmister/wallpanel-android#8] opened 2018-08-07 23:16 UTC
Hi,
my screen doesn't wakeup when motion is detected by the front camera.
it works fine with the old version 0.6. i tried different versions 0.8.2.4 until 0.8.2.8
I see that the device goes completely in sleep because i can also not actived it with the api command.

regards,
Wiebe

**Comment by thanksmister** [comment] 2018-08-08 00:53
Does your device wake when you touch the screen or do you have to use the power button to wake the device?

**Comment by wiebe1971** [comment] 2018-08-08 01:03
No I really have to use the power button.

**Comment by thanksmister** [comment] 2018-08-08 01:08
Then your device is going to sleep and turning off the screen.  You need to adjust your device settings. The device can’t have a lock screen on and it needs to use the Android sleep settings or dream to stay partially awake.  There is a setting in the app to force the screen to stay on but then the screen won’t dim or sleep properly.

**Comment by thanksmister** [comment] 2018-08-08 01:14
This also happens to one of my older devices if I don’t have it plugged in even if I’m running Android day dream without a lock screen set.   So be sure its charging or your phone might go to sleep anyways which means it’s a possibility that it’s not charging fast enough to keep the running applications active so shuts itself down.

**Comment by wiebe1971** [comment] 2018-08-08 01:30
but it works fine in the 0.6 version, with the same device settings.

**Comment by thanksmister** [comment] 2018-08-08 01:36
I think you are referring to the previous project which can be found here: https://github.com/WallPanel-Project/wallpanel-android/releases.  The last release of that project was 0.7b1. I have since forked the project and updated it.   Without knowing which device you have or anything about version 0.6, I can't give much advice other than what I suggested.   I have the app running on old and new devices without any issues but I do have the device sleep option and dream.  Maybe you are running an older device?

**Comment by wiebe1971** [comment] 2018-08-08 02:17
I just downloaded 0.7b1 and that version wakes my screen perfectly. I think I stay with this version then. I'm running Android 5.0.1 Lollipop on an 7" Ematic Tablet 8GB.

**Comment by thanksmister** [comment] 2018-08-08 12:54
What happens when you use the camera test feature in the settings, when you have motion detection and wake on motion set as well?

**Comment by thanksmister** [comment] 2018-08-08 20:34
I discovered the front and back camera were reversed in the last release, maybe before.  So please try the latest update, v0.8.2-beta.9.

**Comment by thanksmister** [comment] 2018-08-09 20:16
I tested the MQTT messages and everything seems to be fine. If you can see your camera during the camera test, then everything should be functional when viewing the dashboard.   I have recently updated the wake lock for waking the application screen.  I will test on an older device running 5.0 to see if my changes make any difference.

**Comment by thanksmister** [comment] 2018-08-10 14:37
I have tested 0.8.3-beta.1 on Android 5.1 (Asus Nexus 7") and I could find no issues with using the camera or detecting motion and reporting it over MQTT.   I think you need to check your MQTT broker information as a first step.  The other option is to use the built in screen saver functionality of the device with day dream so the device doesn't sleep.   Its possible that on your device the camera isn't getting detected, but you mention that you were able to see the camera image and detect motion during the camera test.     At this point I am closing this issue because I am unable to reproduce the issue using the same Android version and I do not have your specific device to test.

**Closed by thanksmister** 2018-08-10 14:37 UTC
