### ISSUE TITLE
On page load error the settings button does not show

### ISSUE THREAD

**Issue by 150d** [thanksmister/wallpanel-android#272] opened 2021-05-24 14:49 UTC
Is it possible to re-enable the back button to access the settings?

I don't need the pin-protected new method, and I already had to reinstall once because the (invisible) floating button isn't available in case of load error.

Regards

**Comment by thanksmister** [comment] 2021-05-24 17:31
Not sure what you mean, the floating button is always available unless you completely disable it.  If you do not want to have the settings button you can just disable it (not make it invisible) and launch the settings with MQTT/HTTP, which bypasses the pin code feature.

**Comment by thanksmister** [comment] 2021-05-24 17:32
The page loading or failing does not change the behavior of the settings button functionality.

**Comment by 150d** [comment] 2021-05-24 17:47
Well, all I can say is that it does here:

I had misconfigured the dashboard URL. The page was reachable, but the parameter contained in the URL led to a error popup (something about a json object - probable nothing to do with Wallpanel). When this popup was confirmed, Wallpanel remained blank (no page loaded) and the button was not accessible.

Bottom line: The floating button may work for some, but I for one wish the old way back. It would be nice if the old behaviour could be re-enabled, even if it wasn't the default any more.

**Comment by thanksmister** [comment] 2021-05-24 18:16
The old behavior is not returning, I will see if I can reproduce the issue.

**Comment by thanksmister** [comment] 2021-05-24 18:28
> I had misconfigured the dashboard URL. The page was reachable, but the parameter contained in the URL led to a error popup (something about a json object - not sure if this was from Wallpanel or from the server.) When this popup was confirmed, Wallpanel remained blank (no page loaded) and the button was not accessible.

Can you provide an example of the URL, just normally misconfiguring a URL does not produce the issue.  This must be something that crashes the browser.

**Comment by 150d** [comment] 2021-05-24 19:03
I just tested the (invalid) URL on a PC - it returned the same message there, so the popup came from the server, not from wallpanel. It looks like any popup will lead to the problem with Wallpanel.

Be that as it may, I reiterate my wish: The new PIN-system is nothing but overhead for me. I personally do not have a use case for it, and it makes my life unnecessarily difficult. This malfunction is just the last straw.

I would strongly appreciate it if the PIN-system could be made optional instead of mandatory.

MfG

**Comment by thanksmister** [comment] 2021-05-24 19:14
I cannot go back to the old system because its not possible to support both.  Honestly, how often do you enter the settings that it has become a such a burden to enter a 4 digit code?    Without the ability to reproduce the URL error, I cannot address it.  Either way the error is with the webpage crashing, not with the application.   The temporary solution is to load a valid URL and if you do not wish to use the settings button, then you can use one of the work arounds mentioned, sending HTTP/MQTT command.  I am going to close this topic now as I don't think its productive.

**Closed by thanksmister** 2021-05-24 19:14 UTC
Labels: investigate

**Comment by 150d** [comment] 2021-05-24 19:27
> I cannot go back to the old system because its not possible to support both. 

I'm not pretending to be knowledgable in Android programming, but how would the floating button prevent one from assigning the function "goto settings screen" to the "back" button as well? It was the case before, why should it be impossible now?

MfG

**Comment by thanksmister** [comment] 2021-05-24 19:29
The back button behavior did not open the setting screen, the previous application had the settings screen as the main screen and this was the reason why we added this feature.  We also wanted to make the app have kiosk features and that includes a setting screen.   I think you are just making an issue when none really exists.  Users enter the code so infrequently that I do not think this is really an issue.   You can disagree, but this ticket has become unproductive.

**Comment by 150d** [comment] 2021-05-24 19:42
> You can disagree, but this ticket has become unproductive.

If you're creating an app for your own needs and are interested in nothing else, then that's just that; nothing I can do about it.

If, on the other hand, you _do_ care about how other users fare with your program, than I need to tell you that the floating-button thing was a bad idea.

Nothing more to be said.

**Comment by thanksmister** [comment] 2021-05-24 19:50
I have explained my decision and given you appropriate answers.  I really don't care to discuss this further as the conversation is not productive and its not even about the making the application better.  It's simply that you feel that some feature that previously existed should come back, that you feel its too difficult to enter the settings with a 4-digit code.    You can easily go back to previous versions of the app before the feature was added.  You even have the option to fork the project and make it the way you want.
