### ISSUE TITLE
MQTT reconnect error

### ISSUE THREAD

**Issue by brahmafear** [thanksmister/wallpanel-android#54] opened 2019-01-28 15:18 UTC
**Describe the bug**
MQTT attempting to reconnect before previous session has timed out (hypothesis) and mqtt server rejects connection due to reused clientID.  

**To Reproduce**
1. Launch app
2. Allow app to connect via MQTT and load web page
3. Click back to access settings page.
4. Click Dashboard to return to web page.
5. "Error connecting to MQTT..."

**Workaround** 
Change clientID when settings page opened.  Or wait a while before reopening dashboard.  

**Expected behavior**
MQTT connection either maintained while settings screen open or cleanly disconnected then reconnected.  

**Smartphone (please complete the following information):**
 - Device: Fire8
 - App version - whatever is latest in Play Store.

**Comment by thanksmister** [comment] 2019-01-28 16:04
Please provide the application version you are using.

**Comment by brahmafear** [comment] 2019-01-28 16:14
About screen says 0.8.5 build 2.

Thanks.

**Comment by thanksmister** [comment] 2019-01-31 15:17
You are a few builds behind, please update and retest.

**Comment by akasma74** [comment] 2019-03-21 21:55
Well, I saw very similar on the latest 0.8.5beta6.
I just turned off WiFi with WallPanel running, got that "Error connecting to MQTT..." and then (after turning WiFi back) sensors' data stopped to appear in mqtt log, but status messages with url/screen brightness were there!
Changing client id helped sometimes.

**Comment by akasma74** [comment] 2019-04-01 22:59
Can confirm the problem is still there on 0.8.6beta1
Tried to restart HA, reboot its host (I'm using Hass.io) to no avail.
The only way to sort it out was to change client id.
Very inconvenient as it might happen when device just reconnects to WiFi..

**Comment by thanksmister** [comment] 2019-04-01 23:15
The original issue no longer occurs, so I am closing this issue as the original reporter no longer responds to this issue and has reported no further issues.   The steps outlined in the ticket do not occur with what you are reporting @akasma74, please provide a new issue to track with specifics about your issue.

**Closed by thanksmister** 2019-04-01 23:15 UTC
Labels: investigate

**Comment by allofmex** [comment] 2019-04-02 08:18
@thanksmister 
I assume this error is because of https://github.com/eclipse/paho.mqtt.java/issues/634
Had the same problem too. It seems to be fixed in paho.mqtt in meantime. Guess it requires a library update for wallpanel..

Another solution may be to change
https://github.com/thanksmister/wallpanel-android/blob/cbde6445e6e0751bdd42e1641cafd3f87156bf45/WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/MQTTService.kt#L167

to 
`
mqttClient = MqttAndroidClient(context, mqttOptions?.brokerUrl, mqttOptions!!.getClientId(), MemoryPersistence())`

Works for my devices, but I don't really know if current FilePersistence is needed for some wallpanel functions.

**Comment by thanksmister** [comment] 2019-04-02 11:13
If we update the Paho library, it will no longer work on older devices due to compatibility issues with a dependency used in the Paho library.   I think it has a minimum requirement of Android SDK version 6.

**Comment by thanksmister** [comment] 2019-04-02 11:13
@allofmex please file a new bug report for the issue you are having and we can consolidate our comments on that report.

**Comment by akasma74** [comment] 2019-04-02 11:14
> If we update the Paho library, it will no longer work on older devices due to compatibility issues with a dependency used in the Paho library. I think it has a minimum requirement of Android SDK version 6.

and without that update we are stuck with mqtt bit that might break every moment. catch 22 :\

**Comment by thanksmister** [comment] 2019-04-02 11:17
Well, so far you are the experiencing an issue that I can not reproduce, I am also running on multiple devices, including a Fire OS.  I have no crash reports either in Firebase for this issue or the line of code you point out.  I will review it, but do please file a new bug report to capture the information here.

**Comment by thanksmister** [comment] 2019-04-02 12:07
Moved to bug report #74
