### ISSUE TITLE
No loading after ssl certificate error

### ISSUE THREAD

**Issue by mnul** [thanksmister/wallpanel-android#35] opened 2018-11-24 19:58 UTC
When I try to load my ssl secured home assistant instance it gives me an ssl error pop-up. 
If I click cancel nothing happens - > ok
If I click on ignore loading doesn't continue - > not okay

It doesn't make any difference if I load my duckdns instance online (where the certificate is valid) or if I try to access it locally (where there is no certificate available)

**Comment by thanksmister** [comment] 2018-11-24 20:16
Thisi s a duplicate of https://github.com/thanksmister/wallpanel-android/issues/33.

**Comment by thanksmister** [comment] 2018-11-29 18:41
You can try the latest release v0.8.5-beta.0

**Closed** 2018-12-16 14:32 UTC
Labels: duplicate
