### ISSUE TITLE
Wallpanel on Nexus 7/Android 6.01

### ISSUE THREAD

**Issue by habitoti** [thanksmister/wallpanel-android#280] opened 2021-06-10 05:22 UTC
I run Wallpanel for a while already on a wallmounted Nexus 7 with Android 6.01. Every now and then I do a clean setup after a factory reset, because for some reason it starts to behave strange. In the past this worked w/o issue, but today Playstore told me that Wallpanel is no longer available for my device. It still reads „Android 4.4“ as minimum version, so what am I missing? It‘s a naked clean 6.01 setup with Chrome and WebView updated to latest versions.
Can you please check whether you mistakenly unchecked Nexus devices in supported devices on Playstore?

**Comment by thanksmister** [comment] 2021-06-10 11:05
This is something that Google has changed, they seem to have stopped supporting some older devices as well as Amazon tablets through the play store.  You will need to install the application manually from the release section of GitHub.

**Comment by habitoti** [comment] 2021-06-10 11:38
Strange enough there are no restrictions on other software for me, so it wasn't somehow generally blocked now on Playstore. I also don't think that Google switches off supported devices just out of the blue w/o notifying (I am a dev. with SW on the Playstore myself...). If so I'd say you've set some flags somewhere that make it fall out of the matrix, but you could easily check in playstore under supported devices and search for e.g. Nexus. Given that OS is more than sufficient, there must be some other constraints that creeped in.
Installed now via APK and it runs fine. Just thinking that you loose some users, because these Nexus devices make some really nice wall panels these days (I made some [advertisement for you even on this Reddit post](https://www.reddit.com/r/homeassistant/comments/nnj4tv/my_pv_dashboard_in_my_kitchen_second_life_for_an/) :-) : ).

**Comment by thanksmister** [comment] 2021-06-10 11:45
Yeah I have checked and it’s happening to Amazon tablets as well for my app.  I haven’t changed support for Wallpanel, it has minimum sdk version 19.   What I have done recently is update the dependencies including Google Services.  I’m Google Play console no devices are restricted.  

I did a search and I can’t find anything related, so for now I am assuming Google has done something on their end.  So far only older devices, Amazon tablets have reported this issue.  

I will continue to investigate, perhaps it’s something obscure such has hardware acceleration.  You’re welcome to look at the manifest and gradadle build file to see if your discover anything.  

For now the simplest solution is to install manually until I can be returned to the matrix.

**Comment by habitoti** [comment] 2021-06-10 11:49
Might even be Google Services then. I usually only update WebView after factory reset. Everything else pulls in too much crap, but maybe next time I also update Google Services for a try. Obviously it's not required, because APK just runs fine w/o updating, but maybe dependency resolution from Playstore is more strict here.

**Comment by thanksmister** [comment] 2021-06-10 11:53
Your solution for waking the device with an external sensor is brilliant, just read through your article.   I am going to do some tests today on my older Nexus 10 device without updating Google Services to see if it can install WallPanel.  I know google reads the manifest for compatibility, perhaps this is the hardware acceleration flag, I recently changed it from false to true because others where having crashes with camera use (which your external sensor idea solves as well :D).

**Comment by thanksmister** [comment] 2021-06-10 11:57
Search of supported devices in Google Play no longer shows Nexus 7 or Nexus 10:

<img width="1319" alt="Screen Shot 2021-06-10 at 8 56 57 AM" src="https://user-images.githubusercontent.com/142340/121520894-d68b6080-c9c9-11eb-9d8f-2c379e79f380.png">

**Comment by thanksmister** [comment] 2021-06-10 11:59
List of unsupported devices:

<img width="1344" alt="Screen Shot 2021-06-10 at 8 58 13 AM" src="https://user-images.githubusercontent.com/142340/121521084-06d2ff00-c9ca-11eb-8164-c4c5503253e4.png">

The reason:

```

This device isn’t supported in your app’s APK manifest. Users with this device can’t install or update your app.```

**Comment by thanksmister** [comment] 2021-06-10 12:00
I am pretty sure its the hardware acceleration flag, let me remove that and update the app in Google Play.  That is the only thing I have changed since the previous updates due to the camera support issues.  There is a flag in the settings that turns on/off this feature as well.

**Comment by habitoti** [comment] 2021-06-10 12:02
However, I do use WallPanel with HW Acceleration switched on in the Wallpanel settings (don't know if this is the same thing than setting in manifest, though...)

**Comment by thanksmister** [comment] 2021-06-10 12:03
In addition to the hardware support flag, I recently added support to allow the microphone on the WebView.

```
  <!-- Permissions to record audio from web page -->
    <uses-permission android:name="android.permission.MICROPHONE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <!-- Features supported -->
    <uses-feature android:name="android.hardware.audio.low_latency" />
    <uses-feature android:name="android.hardware.audio.pro" />
    <uses-feature android:name="android.hardware.microphone" />

```

**Comment by thanksmister** [comment] 2021-06-10 12:03
The only way to test is to upload a new version to the store and then see if the device is supported.  I will let you know if I resolve this.   Thanks for help!

**Comment by habitoti** [comment] 2021-06-10 12:04
Ok

**Comment by habitoti** [comment] 2021-06-10 12:23
One other thing I noted with the latest Beta-APK I am now using: the Rest command for waking the screen does no longer work. It responds 200/result:true, however the screen doesn't switch. Any other changes in the SW that I haven't yet considered? It's not the first time I did this whole clean setup procedure, but so far I never had to change anything in the device setup other than installing Wallpanel, allowing the RestAPI and setting the dashboard URL.

**Comment by thanksmister** [comment] 2021-06-10 12:42
You need to send a wake command differently, now adds a time to wake.  This was a feature change so you can wake the device for a set amount of time without the screensaver (built-in) activating.    If yo just send wake/true the screen wakes until the screensaver (user inactivity time) kicks in only.       

I have fixed the manifest issue, it was the new microphone permissions, they needed the required=false flags or they will exclude devices without those features.  That was a mistake on my part.

**Comment by thanksmister** [comment] 2021-06-10 12:43
For waking the screen, send something like this `{"wake": true, "wakeTime": 180}` to wake for 3 minutes, or whatever, it's in seconds.

**Comment by thanksmister** [comment] 2021-06-10 12:52
I think if you just send `{"wake": true}`, the time is set to 0, which makes no sense since it won't wake the device.  It was set to 30 seconds default, but it should be set to the user inactivity time, the timeout you set in the settings to turn on the sceensaver or let the screen sleep.    I will fix this by adding either a 30 second default wake time or use the settings for the user inactivity time.

**Comment by habitoti** [comment] 2021-06-10 13:01
Yeah, I saw that on another issue and as I wrote, it doesn't matter. Tried with different wakeTimes, no change. It also seems to be a different issue altogether, as other commands also no longer work. reload, settings, speak -- none do anything, but all respond 200. RestAPI is enabled on port 2971. But Wallpanel just ignores everything.

**Comment by thanksmister** [comment] 2021-06-10 13:02
I have tested these with the rest command, I was able to use speech without issue and wake.

**Comment by thanksmister** [comment] 2021-06-10 13:34
This is working for me for TTS: 

```curl --location --request POST 'http://192.168.232.2:2971/api/command' \
--header 'Content-Type: application/json;charset=UTF-8' \
--data-raw '{
    "speak": "\xc2\xa1\x41\x6c\xc3\xb3\x21 mundo"
}```

**Comment by thanksmister** [comment] 2021-06-10 13:37
I am also able to wake the device: 

```
 curl --location --request POST 'http://192.168.86.25:2971/api/command' \
--header 'Content-Type: application/json;charset=UTF-8' \
--data-raw '{
    "wake": true       
}'
{"result":true}%   
```

**Comment by thanksmister** [comment] 2021-06-10 13:39
This a stupid question, but did you check the IP address in the settings for your device, on the http screen I post the address of the device with the port.   I know you said you clean your device, perhaps it has a new IP address.  Yeah, I am sure you checked this, but you know... haha.

**Comment by habitoti** [comment] 2021-06-10 13:46
The device gets a fixed IP (based on MAC) from my router, but yes...I also checked to be sure  :-)
And as said, using Postman instantly returns 200 and a proper result json ({"result": true"}). If I e.g. don't set the content type properly ("application/json"), it would also correctly respond with "result": false.
I have a bunch of ready-made Postman templates from when I initially tried the RestAPI, and all of them don't do anything (like I said reload, speak etc.) They all worked until yesterday...
Just seeing Betas in Github. Is there a list of releases also, so I can just try a Playstore/release version from like 4-6 weeks ago, if it makes a difference?

**Comment by thanksmister** [comment] 2021-06-10 13:58
You can go back to previous releases in the store, but I am not able to reproduce any issue on the current version in Google Play store that was released in the last hour.  The app is always in beta, just avoid the pre-release versions.  I will be posting the current play version to github in a few.

**Comment by thanksmister** [comment] 2021-06-10 14:14
Here is my postman with wake, just using content type json header: 

<img width="1173" alt="Screen Shot 2021-06-10 at 11 13 14 AM" src="https://user-images.githubusercontent.com/142340/121540498-e6607000-c9dc-11eb-9c4c-cfa9fae9790e.png">

**Comment by thanksmister** [comment] 2021-06-10 14:14
These are my headers: 

<img width="1200" alt="Screen Shot 2021-06-10 at 11 14 20 AM" src="https://user-images.githubusercontent.com/142340/121540631-04c66b80-c9dd-11eb-83f7-b0b513b535c1.png">

This worked on the latest release, that is up in the release section now.

**Comment by thanksmister** [comment] 2021-06-10 14:16
With speak command:  

<img width="1178" alt="Screen Shot 2021-06-10 at 11 15 46 AM" src="https://user-images.githubusercontent.com/142340/121540877-36d7cd80-c9dd-11eb-9470-9956d43c37c0.png">

TTS may be related to Google Play services, but I think the app will display an error if not supported.

**Comment by habitoti** [comment] 2021-06-10 14:17
Yeah, same here.

![image](https://user-images.githubusercontent.com/220421/121541003-33f1d280-ca07-11eb-9ad3-16e97cf06faf.png)

It's just not doing anything for any of the commands...

**Comment by thanksmister** [comment] 2021-06-10 14:20
I can't reproduce the issue, did you try with https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.5.3?  That is the latest release.   Maybe some parsing json error, but the commands have not been changed in the way they parse json for many releases.  You can try with an old release, before I used the code to open the settings: https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.3.1

**Comment by habitoti** [comment] 2021-06-10 14:21
Yes, as soon as my "day job" lets me I will try different versions. Need to walk to the device, as it's glued to the wall ;-)

**Comment by thanksmister** [comment] 2021-06-10 14:22
Yeah no issue, maybe you should try with a basic command, TTS could be dependent on Google Services.   Try just a different URL  `{"url": "http://www.google.com"}`.

**Comment by thanksmister** [comment] 2021-06-10 14:31
No, that is what we return on success.   My point about using the url command is that it doesn't depend on Google Services, and it's not the revamped wake command.  It's like a baseline test.  If this doesn't work, it's you man, not me (maybe).

**Comment by habitoti** [comment] 2021-06-10 14:50
Setting the URL doesn't return/times out.

**Comment by thanksmister** [comment] 2021-06-10 14:53
That’s really strange, it works as expected from postman.  Check your headed maybe?  Make sure you have correct quotes.

**Comment by habitoti** [comment] 2021-06-10 14:57
You're right, fck German quote signs that look exactly the same... ;-)   (should it hang then, though?)

Anyway, same here with correct quotes. Returns 200/result:true, but nothing happens. It's just continuing to show my dashboard.

**Comment by thanksmister** [comment] 2021-06-10 17:49
That's not the behavior, a wake simply removes the screensaver.  There is a separate call to reload and that is not called at any time during a wake.    This might be some connection issue with HA, is it a reload of the page or do you see the connection reload in HA.   Maybe WebView support?

**Comment by habitoti** [comment] 2021-06-10 18:13
Device should be sleeping, I use no screensaver. Waking generally seems slower now (before it was switched instantly on, now it takes like 5 secs). Just had a complete crash also during sleep, so I woke up device manually and Wallpanel has crashed and normal homescreen was shown.
Might be WebView, for sure. It‘s the major difference (beside latest Wallpanel), as I used a 2 month old WebView version before, but today after factory reset updated to latest one.
Tbh it‘s basically unusable now. Was happy with my dashboard running 24x7 w/o any issues, waking up instantly on motion detection (and according Rest wakeup call then), no full reloads then. 
Never change a running system :-)

**Comment by thanksmister** [comment] 2021-06-10 19:09
The WebView is device specific or updated on the device.   If you can't use the update then switch to an older version. I don't see how its the app issue unless its related to hardware acceleration.  There is no reload on any of my devices when I send a wake command, it seems like it has some type of slow connection.

**Comment by thanksmister** [comment] 2021-06-10 19:49
You can install WebView component or update it independent of the OS, there is a repository some place for them.  You can also try with Fully Kiosk, see if has issues rendering the same page.  I assume that it does since it is also dependent on WebView.  Trying to rule out app specific issues.

**Comment by thanksmister** [comment] 2021-06-10 19:53
I released a new version with some other fixes for unrelated changes.   I reverted the manifest to what it was in previous releases, with the addition of only the audio permissions (optional).   https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.5.4

**Comment by habitoti** [comment] 2021-06-10 20:51
Well, I am not blaming Wallpanel at all. As said above, there is a strong likelihood that it‘s related to WebView. It is updated way too often, IMHO. There were dozens of updates this year alone, and it‘s even unclear what changes come with each of it. I know that site with the previous versions, and I will try a few of those past ones next. I think the whole exercise is way more frustrating knowing how perfectly it all worked before, than if it just wouldn‘t work at all in the first place. Would be easier to accept then :-( 
The one thing I don‘t quite get is why so often (not every time, though) the whole Wallpanel app restarts completely on remote wakeup. This means it was still alive when the wakeup call came in, but then doing (or trying to do) its thing it restarts. It wouldn‘t restart if it would crash then, or? What would be a reason or explainable case where it reloads or restarts completely?

**Comment by habitoti** [comment] 2021-06-10 21:09
Looking closer it seems rather like the whole website is reloaded as if it would have been freshly started, i.e. as if the Wallpanel was just started and loads the dashboard from scratch, incl. authenticating, homeassistant splash screen etc. It might well be that Wallpanel doesn‘t even know and behaves totally normal, while the WebView is just completely mad.

**Comment by habitoti** [comment] 2021-06-10 21:43
Unlikely. I have a very stable dense Unify WiFi mesh attached to Gigabit LAN around the house, and I am usually not experiencing any WiFi issues anywhere around my premises. Unless sth. in the Nexus broke (maybe HW-wise…it‘s 8 years old now…) I wouldn‘t expect connection issues on the device. 
What I just noticed that I seemingly didn‘t block internet access for the device right after the Wallpanel APK installation, and the device took its chance and updated the whole Google crap and other stuff a bit later. So that‘s also a noticeable difference to how I usually run the device, because I normally don’t allow Internet access for it after I installed only those SW that I need for the dashboard usecase. So I‘ll better try another clean factory reset and new setup.

**Comment by thanksmister** [comment] 2021-06-11 15:04
We have a new feature that was added, which reloads the webpage if a network connection is encountered.  I am pretty sure for some reason your device WiFi may be disconnecting when the screen sleeps.   There are apps that ping the connection to keep it live, previously this would not have been an issue since the page did not have an option to refresh on disconnect.   For commands to work properly, wifi should not be lost when the device sleeps.  Maybe this was a change or setting on your device during your last fresh install.

**Comment by habitoti** [comment] 2021-06-11 15:31
Is that a switchable feature? Can I revert to the previous behaviour for a try?
The Android device has a setting to control Wifi on sleep, but it's set to ALWAYS ON per default, so Wifi shouldn't go away while sleeping.
I also contacted the Homeassistant folks to check with them if there was any change in the dashboard loading behaviour. Maybe with a fast device you wouldn't even bother. My iPad Pro loads such a complex dashboard in a second, but the old Nexus needs almost a minute to setup the 3 Grafana charts from scratch.

**Comment by thanksmister** [comment] 2021-06-11 15:39
It is not a feature that can be turned off.  We may have to make that an option.   But it does appear that is what may be happening, are you sure there is no network disconnect on that device?    I am pretty sure this is setting the refresh, but it could be a side effect of screen sleep/wake doing a brief disconnect, then reconnect.    I think making this optional is the best way to handle multiple home automation platforms.  Some platforms do a good job of refreshing their own webpage.

**Comment by habitoti** [comment] 2021-06-11 16:19
I am not totally sure. No clue where I could look it up after the fact. From the settings I‘d say it shouldn‘t, and network quality shouldn‘t be an issue at all, as said above. Just re-checked on the device, and „Keep Wifi on during sleep“ is set to „Always“.

I‘d say if you have a stateless (or session-less) dashboard, an overarching refresh doesn‘t make much sense. You could at any point just have it do the next data reload even if there was a Wifi interruption in between. Also if the dashboard UI has it‘s own way of dealing with connection issues (if required), any global interference does probably more harm than good. So I agree, making that an option would help in such cases where you‘d just rely on the „guest UI“.

**Comment by thanksmister** [comment] 2021-06-11 16:21
Ok, agreed.  I will make that an option and release an update. Hopefully this gets you up and running again, got to keep those old Nexus 7 devices in service.  :D

**Comment by thanksmister** [comment] 2021-06-11 17:34
OK, new pre-release (not in Google Play) with new setting Network Disconnect, turn this off if you do not want to auto-refresh on network changes.    Now the page will refresh if it initially loads the app without a network connection, there is a special network error page shown, but I don't think you have ever seen that in your setup. 

https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.5.5

**Comment by habitoti** [comment] 2021-06-11 17:54
Probably not, but just to be sure: you‘re not checking connectivity by pinging Google or sth., right? Because e.g. in my case the device can only reach the Homeassistant server, nothing else (esp. not the Internet).

**Comment by thanksmister** [comment] 2021-06-11 18:04
We are reading the state of the device connection, wifi or network, from the Android SDK.

**Comment by habitoti** [comment] 2021-06-11 18:22
Awesome, I just installed 0.9.5.5 and switched the refresh on disconnect off. Let‘s see how it behaves now :-)

**Closed** 2021-08-30 20:51 UTC
