### ISSUE TITLE
Microphone permissions to webview

### ISSUE THREAD

**Issue by scb00** [thanksmister/wallpanel-android#238] opened 2021-01-18 09:34 UTC
**Problem**: HTML5 speech recognition API is not working in the embedded website. Maybe because Webview does not implement it, but it could be just a permissions problem.

**Solution**: maybe by adding microphone permissions to the app (and Webview?) speech recognition would work. Or at least, mic recording from HTML.

Other solution, if this does not work, would be to add a speech recognition button that used native Android API, able to both be triggered by and send results to MQTT.

**Testing**: It may be tested with this demo page as panel content: https://www.google.com/intl/en/chrome/demos/speech.html 

More context: See my original post at the community site:
https://community.thanksmister.com/t/speech-recognition/106

**Comment by thanksmister** [comment] 2021-01-18 11:55
This seems like a duplicate of an older issue, but nobody has put forth a PR to update the micrphone permission.

**Comment by thanksmister** [comment] 2021-03-09 14:23
Closing as duplicate

**Closed by thanksmister** 2021-03-09 14:23 UTC
Labels: duplicate

**Comment by eporsche** [comment] 2023-12-01 11:01
The duplicate is gone, could this issue bee reopened?
