### ISSUE TITLE
Unable to load any page in WallPanel

### ISSUE THREAD

**Issue by AaronHolbrook** [thanksmister/wallpanel-android#119] opened 2019-09-22 21:48 UTC
**Describe the bug**
Unable to load any page/site in wallpanel. I have tested: 
* my local Hassio site (http://hass.home)
* IP of the hassio site (http://192.168.1.16)
* https://google.com 
* http://example.com
* https://example.com

**To Reproduce**
1. Go to 'Dashboard URL'
2. Set to 'https://example.com'
3. Click 'Dashboard' to load browser'
4. See: 'Loading 10% http://example.com/
5. nothing else happens

**Expected behavior**
The desired site/page to load

**Screenshots**
![IMG_1053](https://user-images.githubusercontent.com/953022/65394877-77e70480-dd58-11e9-99b9-2809f1ecf05a.jpeg)

**Smartphone (please complete the following information):**
 - Device: [Lenovo Tablet M10 (TB-X505F)]
 - OS: [Android 9]
 - Version [0.8.7 Build 4]

**Additional context**
I have tested this on both my home wifi network and my phone's hotspot to ensure that the network wasn't the issue.

I can load all pages/sites listed above in the default chrome browser on the device.

**Comment by AaronHolbrook** [comment] 2019-09-23 01:50
I'm thinking this is probably because of ssl / https support in Android 9.

https://stackoverflow.com/questions/52594637/webview-is-not-loading-page-in-android-9-0
https://developer.android.com/about/versions/pie/android-9.0-migration

**Comment by AaronHolbrook** [comment] 2019-09-23 10:40
I figured out what is happening.

Android 9 implements Chrome as the default webview renderer, except most applications haven't accepted that/made it work/whatever, so they don't load the webview at all. 

By uninstalling chrome it forces the default android webview renderer to be used and this works once again. The only issue is now that I don't have access to Chrome, but seeing as this is to be used on the wall, that's not a big deal. I installed a different browser to use the web.

This should probably still be addressed, and at the very least documented for anyone new coming in, as I spent a good number of hours running around in circles trying to understand why this wouldn't work.

**Comment by thanksmister** [comment] 2019-09-23 12:47
I tested on a Google Nexus 5 running Android 10.  I have Chrome browser installed and and loaded https://www.google.com (with its ssl).  I was not able to reproduce your issue.   I do not think there is a connection between having Chrome installed and the application using the Android WebView component.    The WebView component is a separate part of Android.  You can find it on the Google Play https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en. 

You may be experiencing SSL issues if you try to load a site that has a self-signed certificate.  That would require the application to manually add your certificate to run.  But loading any site (like google.com) with a certified SSL certificate causes no issues.    Locally you can load HA on your local network if you did not have an SSL self-signed certificate installed. 

Looking at the Google Play store, of the 12000 active devices, 2000 of those are running Android 9 or above.  I do not see any crashes or have others reporting this issue.  So this makes me think this issue has something to do with your setup or device. To me this seems like a SSl issue with whatever site you are using. 

Possibly as you described in your previous link for Android 9, there needs to be an added value to the manifest in order to run local sites without http, but I have not experienced that issue either.  I can connect to my HA on my local http address without issues, but I do not use SSL on my HA because its running on my local network behind my firewall. 

Are you having issues loading google.com when you have the application and Chrome browser installed?   Is the site you are trying to load local with an SSL?

**Comment by thanksmister** [comment] 2019-09-23 13:57
The only update we could make is adding  android:usesCleartextTraffic="true" to the manifest, we obviously cannot add a local domain to the manifest as everyone who uses the application will have a different local domain.   I updated the application to API version 28 and added android:usesCleartextTraffic="true" to the manifest.   After I test this, I will push out an update, as long as this does not interfere with older devices, there should be no issue adding android:usesCleartextTraffic="true", it requires API version 23 or older and the app supports older API, going back to API 16.

**Comment by AaronHolbrook** [comment] 2019-09-23 14:33
Hey @thanksmister thanks for the quick response!

I completely understand it _could_ be specific to the device I am attempting this on. However, I have no other Android device to test this out on.

I know it's not https specific, because I attempted to load http://example.com, https://example.com, and https://google.com all of which either have no ssl, or legitimate ssl certificates. I also do not have a self signed cert or any cert for my local Hassio setup yet, so I know it's not SSL related.

I had issues with multiple apps, not just this one when attempting to load any page in a webview app (Fully kiosk browser, another Kiosk app) and they all acted the same way as WallPanel, the just showed a white screen with no indication of anything happening.

As soon as I disabled Chrome, the fallback Android Webview system immediately began being used and WallPanel is now working perfectly.

Again, all I know is what I have and what action I took and now it is working correctly.

> Are you having issues loading google.com when you have the application and Chrome browser installed?

Yes, see above.

> Is the site you are trying to load local with an SSL?

No, see above.

>  we obviously cannot add a local domain to the manifest as everyone who uses the application will have a different local domain

Yea, I totally get that, I wasn't suggesting that needed to happen, I was just referencing some potential items I saw in my research.

Appreciate all your hard work @thanksmister, this app is wonderful!

**Comment by thanksmister** [comment] 2019-09-23 14:39
It seems to me that this is not an application related issue.   We have a lot of Android 9 users and I tested on a stock Android 9 device.   You are having the issue on multiple apps, that is a red flag, it tells me your Lenovo device is the most likely issue and not the apps.   I am not sure how I can address your specific issues with my application.  I do not think that for the majority of users they experience the issue with Chrome and WebView running on the same device.   You might look on Google Play and see if you can update your WebView component.   There is no other component to render webpages inside an Android app.

**Comment by AaronHolbrook** [comment] 2019-09-23 15:18
This is a stock Lenovo device purchased yesterday from Best Buy running Android 9.

It may be just related to this device, but I'd be on the lookout for potential future issues, in case there are steps that need to be taken to be forward compatible.

> You might look on Google Play and see if you can update your WebView component.

I did just that, and until I removed Chrome, I was unable to do anything with the WebView component, it simply said 'disabled'.

I'm all good moving forward, you can close this if there's nothing for you to do. Removing Chrome fixed my issue and I'm able to use WallPanel without any issues now.

**Comment by thanksmister** [comment] 2019-09-23 17:00
The issue I have is that the app is already running on 2000 Android 9 devices, so this should have been an issue already, Android 9 has been out for a while.   I imagine your Lenovo isn't running stock Android, that may be something to look at.   I will close this issue for now, but it is here archived for others to find if they run into this issue.  Thanks for all the great input on the issue.

**Closed by thanksmister** 2019-09-23 17:00 UTC
