### ISSUE TITLE
microphone not available?

### ISSUE THREAD

**Issue by dedepene** [thanksmister/wallpanel-android#95] opened 2019-06-18 08:47 UTC
**Describe the bug**
So the microphone access for HA conversation mode is still a feature request or is there a way to enable it now?

**Smartphone (please complete the following information):**
 - Device: HTC Nexus 9
 - OS: Android

**Comment by thanksmister** [comment] 2019-06-18 12:14
Duplicate of #1

**Closed by thanksmister** 2019-06-18 12:14 UTC
