### ISSUE TITLE
MQTT commands no longer work on Nexus 7

### ISSUE THREAD

**Issue by LifeBandit666** [thanksmister/wallpanel-android#278] opened 2021-05-31 15:58 UTC
**Describe the bug**

**To Reproduce**
send wake command, no wake screen

What should it do? screen wakes like it always has done

**Smartphone (please complete the following information):**
 - Device: Nexus 7
 - OS: Lineage OS
 - Browser Chrome
 - Version just updated from play store yesterday to try and stop the app crashing every 3 minutes
**Additional context**
I can see the command on MQTT Explorer, it's defo being sent, it's just not working as it used to. same command I've been sending from node red for the last 6 months. { "wake": true }

**Comment by thanksmister** [comment] 2021-05-31 16:19
This feature has gone through some changes in the latest release.   We now pass in a wake time that suspends the the screensaver for the set amount of time.    

If you not include a time, then it wakes the screen temporarily until the screensaver is again active.    You should send a time as outlined in the wiki: https://github.com/thanksmister/wallpanel-android/wiki/MQTT-and-HTTP-Commands.     

Sending just `{ "wake": true }` will temporarily awake the device, it will again sleep once the timer for user inactivity activates.  If this new behavior is not working as described, please return here to add additional information to the ticket.

**Comment by LifeBandit666** [comment] 2021-06-01 14:53
I wondered if something had changed! Well it kinda works with my old command if the screensaver is active, but not when android's sleep mode is active. The new command (pasted directly from the link you provided) wakes the device from sleep mode (android sleep mode not the app's) and sets the android sleep mode timer to 3 minutes, not the app's screensaver.

I just tested it out, setting Wallpanel screensaver (clock) to 15 seconds and Android sleep to 30 seconds. Like I say, just using "wake" wakes it from screensaver but not Android sleep, and using "wakeTime" awakens from android Sleep mode but doesn't wake from the screensaver.

Ideally the command should wake from sleep mode and wake the screen saver too. For now I'll just get rid of the screen saver and set the wakeTime to 300 so it's on while my lights are on.

**Comment by thanksmister** [comment] 2021-06-01 15:39
OK, I will look into why its not also waking the device screensaver.  You are using Daydream?   I think we need some other type of wake lock.

**Comment by thanksmister** [comment] 2021-06-01 16:03
If you send wake command `{"wake": true, "wakeTime": 0}`,  zero delay value, you will have the same exact behavior as before.  There was no change for that behavior.  You should not run both the device screensaver and the built-in screensaver, it's one or the other.   Sending `{"wake": true, "wakeTime": 180}` and using the screensaver will remove the built-in screensaver.  I do not know yet if this turns off the device screensaver, it should.    `{ "wake": true }` is not a valid command any longer.   What we did is delay the screensaver becoming active again for the "wakeTime", but this would not effect your device screensaver, I have to look into how to achieve this.    There is also some other issues if you are using motion/face wake, it resets the screensaver value.

**Comment by LifeBandit666** [comment] 2021-06-01 18:20
I'm not using the motion/face wake feature at all now. I thought it was eating power (it wasn't, it was keep awake doing that) and started triggering it with an MQTT command based off my Aqara motion sensor.

I turned off Keep Awake when I realised I could have no lock screen at all on the tablet and the wake command will wake the tablet, not just a screen saver of the app.

In my testing today my original {"wake": true} woke the screensaver (that was set to come on after 15 seconds) and not the Android sleep.

The {"wake": true, "wakeTime": 180} doesn't wake the screensaver but does wake the Android sleep. My Android sleep was set to 30 seconds but seemed to be far longer when I sent the command. Therefore it must be changing the Android built in sleep, whether by design or not. 

" What we did is delay the screensaver becoming active again for the "wakeTime", but this would not effect your device screensaver"

What it does not do is change the time for when the app's screen saver kicks in. That was consistently 15 seconds throughout my tests this afternoon. Whether I sent wake: true or that with waketime: 180, the screen saver kicked in after 15 seconds.  wakeTime seemed to effect the devices built in screen sleep.

I'm good with how it's set up now, just removing the screensaver, but I will just give you the use-case for using both so you're aware; I had no clock downstairs where the tablet is, and didn't know how to add one to the Lovelace. So I liked that I could have the screen wake as I walk past, and if I glanced back a bit later I could check the time because the screensaver had kicked in. Keeping the screen awake used more power than I could get into the aging tablet I'm using, so I needed to shut the screen off when not in use to conserve power/actually charge the bloody thing. So I just set the sleep time to 5 minutes.

Now I've managed to add a clock to the Lovelace view so I have no need for the screensaver anymore really, it was just still on. So the current behaviour works out fine for me now, as long as I can wake the screen with an MQTT command I'm good.

Regarding that, I don't understand why you've changed a basic command. Could we not have the screensaver delay as a separate command and keep the wake command basic? We can send more than one command after all.

**Comment by thanksmister** [comment] 2021-06-01 19:16
I have tested the feature with a device running Daydream (with a clock screensaver) and it seems to be working as expected.   I tested with the regular screensaver and also works as expected.   I don't have plans to support the use case for using both screensavers types.     The screen wake will use more power, it is why I recommend using the device screensaver as it dims the device to save energy.    Look to see if your device screensaver also has a clock option as mine does, maybe that will help.

**Comment by LifeBandit666** [comment] 2021-06-01 19:28
Now I've managed to add a clock to the Lovelace view so I have no need for the screensaver anymore really, it was just still on. So the current behaviour works out fine for me now, as long as I can wake the screen with an MQTT command I'm good.

Regarding that, I don't understand why you've changed a basic command. 
Could we not have the screensaver delay as a separate command and keep the wake command basic? 

We can send more than one command after all.

{"wake": true"}
{"wakeTime": 180}

2 separate commands make it more modular, encompassing more use cases, while also having less users, like me, confused as to why their screen isn't waking up all of a sudden.

**Comment by thanksmister** [comment] 2021-06-01 19:36
Just send `{"wake": true, "wakeTime": 180}` or send `{"wake": true, "wakeTime": 0}` to produce the same results.   Optionally you can send `{"wake": true}` and will be same as `{"wake": true, "wakeTime": 0}`

**Comment by thanksmister** [comment] 2021-06-01 19:48
I have a new version that was tested with the device screensaver, some adjustments to keep device awake on user interaction until wake time ends.  https://github.com/thanksmister/wallpanel-android/releases/tag/v0.9.5.1

**Comment by thanksmister** [comment] 2021-06-11 15:01
Seems duplicate of https://github.com/thanksmister/wallpanel-android/issues/280

**Closed** 2021-06-11 15:02 UTC
Labels: bug
