### ISSUE TITLE
Add Wiki\Community section to GitHub

### ISSUE THREAD

**Issue by mikebol** [thanksmister/wallpanel-android#252] opened 2021-03-23 17:53 UTC
Since you've taken over the WallPanel project, how would you feel about adding a Wiki with **current** examples and a discussion forum?  So many of the examples and discussions on other forums are significantly dated and no longer relevant.  

As an example, I'm looking for current examples on how to use "intent:" to launch Spotify on a Fire tablet with HomeAssistant.  These examples are years old and reference weblink which has been deprecated.

Thanks for considering, Mike

**Comment by thanksmister** [comment] 2021-03-23 19:32
Yeah, well the issue is who is going to setup and maintain all that, as you can see the older wiki fell to dust.  I have tried to add applicable examples to the documentation and direct users to that as needed.  Seems like a wiki would be a duplicate of the documentation.

**Comment by thanksmister** [comment] 2021-03-25 11:37
You are welcome to help, if I create the wiki, you can set up the initial examples?

**Comment by thanksmister** [comment] 2021-03-25 11:42
I added the Wiki feature to the repository.  I guess we can migrate most of the related documentation to the wiki.

**Closed** 2021-03-30 21:49 UTC
Labels: help wanted
