### ISSUE TITLE
Feature Request: Activate / Deactivate wallpaper screen saver option via API call

### ISSUE THREAD

**Issue by DomoTND** [thanksmister/wallpanel-android#263] opened 2021-04-11 08:28 UTC
Hi, I think it would be very useful to be able to set on/off the wallpaper screen saver option in the app config via API call (by sending a MQTT command request, for instance). This would allow us to change the screensaver type at any time as needed. For example, showing the wallpaper screen images during the day and just keeping a blank screen with the clock at night. Would it be easily possible?

**Comment by thanksmister** [comment] 2021-05-18 13:49
Duplicate of https://github.com/thanksmister/wallpanel-android/issues/264

**Closed** 2021-05-18 13:49 UTC
